services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - PORT=3000
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:3000"

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - PORT=3000
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - app_blue
      - app_green
    ports:
      - "8080:8080"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - RELEASE_ID_BLUE=${RELEASE_ID_BLUE}
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx_logs:/var/log/nginx
    command: /bin/sh -c "envsubst '$$ACTIVE_POOL $$RELEASE_ID_BLUE' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  alert_watcher:
    build: ./watcher
    container_name: alert_watcher
    restart: always
    depends_on:
      - nginx
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
    volumes:
      - ./nginx_logs:/var/log/nginx

volumes:
  nginx_logs:
